# Generated by Django 4.2.20 on 2025-05-07 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('calibration_range_max', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='punto máximo')),
                ('calibration_range_min', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='punto mínimo')),
                ('uncertainty', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Incertidumbre')),
                ('error', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Error')),
                ('link', models.CharField(verbose_name='Link')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Calibración',
                'verbose_name_plural': 'Calibraciones',
            },
        ),
    ]
