# Generated by Django 4.2.20 on 2025-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibration",
            name="link",
        ),
        migrations.AddField(
            model_name="calibration",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="calibrations",
                verbose_name="Certificado",
            ),
        ),
    ]
