# Generated by Django 4.2.20 on 2025-05-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibration", "0002_remove_calibration_link_calibration_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibration",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="calibrations/",
                verbose_name="Certificado",
            ),
        ),
        migrations.AlterField(
            model_name="calibration",
            name="number",
            field=models.CharField(max_length=10, unique=True, verbose_name="Número"),
        ),
    ]
