# Generated by Django 4.2.20 on 2025-05-07 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0002_alter_equipment_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasuringEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meassurment_range_max",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="rango máximo"
                    ),
                ),
                (
                    "meassurment_range_min",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="rango mínimo"
                    ),
                ),
                (
                    "resolution",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="resolution"
                    ),
                ),
                (
                    "emp",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="EMP"
                    ),
                ),
                (
                    "magnitude",
                    models.CharField(
                        choices=[
                            ("LNG", "Lenght"),
                            ("CRN", "Time"),
                            ("BAS", "Mass"),
                            ("FOT", "Speed"),
                            ("TEMP", "Temperature"),
                            ("MULT", "Electric"),
                        ],
                        default="FOT",
                        max_length=50,
                        verbose_name="Magnitud",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento de medición",
                "verbose_name_plural": "Instrumentos de medición",
            },
        ),
    ]
