# Generated by Django 4.2.20 on 2025-05-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_alter_equipment_code_alter_equipment_id"),
        ("measuring_equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuringequipment",
            name="equipment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="equipment.equipment",
                verbose_name="Equipo",
            ),
        ),
    ]
