# Generated by Django 4.2.20 on 2025-05-07 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("area", "0002_alter_area_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Equipo")),
                ("model", models.CharField(max_length=50, verbose_name="Modelo")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código"
                    ),
                ),
                ("serie", models.CharField(max_length=20, verbose_name="Serie")),
                (
                    "mannufacturer",
                    models.CharField(max_length=50, verbose_name="Fabricante"),
                ),
                ("installed", models.DateField(verbose_name="Instalación")),
                ("purchased", models.DateField(verbose_name="Adquirido")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("accesories", models.TextField(verbose_name="Accesorios")),
                (
                    "manteinance_interval",
                    models.IntegerField(verbose_name="Mantenimiento | Meses"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IM", "Measurement Instrument"),
                            ("MI", "Industrial Machine"),
                        ],
                        default="MI",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="equipments", verbose_name="Imágen"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="area.area",
                        verbose_name="Area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
            },
        ),
    ]
