# Generated by Django 4.2.20 on 2025-05-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_equipment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipments/", verbose_name="Imágen"
            ),
        ),
    ]
