# Generated by Django 4.2.20 on 2025-05-07 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_equipment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
