# Generated by Django 4.2.20 on 2025-05-07 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Descripción")),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positiones",
            },
        ),
    ]
