# Generated by Django 4.2.20 on 2025-05-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "Cargo", "verbose_name_plural": "Cargos"},
        ),
    ]
