# Generated by Django 4.2.20 on 2025-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0002_alter_position_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, unique=True, verbose_name="Código"
            ),
        ),
    ]
