# Generated by Django 4.2.20 on 2025-05-07 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("liable", "0001_initial"),
        ("equipment", "0002_alter_equipment_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="Número")),
                ("date", models.DateField(verbose_name="Fecha")),
                ("diagnostic", models.TextField(verbose_name="Diagnóstico")),
                ("activities", models.TextField(verbose_name="Actividades")),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                        verbose_name="Equipo",
                    ),
                ),
                (
                    "liable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liable.liable",
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
            },
        ),
    ]
