# Generated by Django 4.2.20 on 2025-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="category",
            field=models.CharField(
                choices=[("P", "Preventive"), ("C", "Corrective")],
                default="P",
                max_length=10,
                verbose_name="Categoría",
            ),
        ),
    ]
