# Generated by Django 4.2.20 on 2025-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_maintenance_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="number",
            field=models.CharField(max_length=10, unique=True, verbose_name="Número"),
        ),
    ]
