# Generated by Django 4.2.20 on 2025-05-07 02:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=20, verbose_name='Nit')),
                ('telephone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
