# Generated by Django 4.2.20 on 2025-05-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Proveedor", "verbose_name_plural": "Proveedores"},
        ),
    ]
