# Generated by Django 4.2.20 on 2025-05-07 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Liable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, verbose_name="Código"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nombre"),
                ),
                (
                    "lastName",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apellidos"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                ("telephone", models.CharField(max_length=10, verbose_name="Teléfono")),
                (
                    "workstation",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="liables",
                        verbose_name="Imagen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable",
                "verbose_name_plural": "Responsables",
            },
        ),
    ]
