# Generated by Django 4.2.20 on 2025-05-07 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("liable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liable",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, unique=True, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="liable",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                unique=True,
                verbose_name="Correo Electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="liable",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
