# Generated by Django 4.2.20 on 2025-05-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0003_alter_position_code"),
        ("liable", "0002_alter_liable_code_alter_liable_email_alter_liable_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="liable",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="position.position",
                verbose_name="Cargo",
            ),
        ),
        migrations.AlterField(
            model_name="liable",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="liables/", verbose_name="Imagen"
            ),
        ),
    ]
