# Generated by Django 4.2.20 on 2025-05-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0003_alter_position_code"),
        ("liable", "0003_liable_position_alter_liable_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liable",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="position.position",
                verbose_name="Cargo",
            ),
        ),
    ]
