# Generated by Django 4.2.20 on 2025-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liable", "0004_alter_liable_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="liable",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
    ]
