# Generated by Django 4.2.20 on 2025-05-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liable", "0005_liable_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liable",
            options={"verbose_name": "Personal", "verbose_name_plural": "Personal"},
        ),
    ]
